# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-03 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_grade_gen', '0002_autogencourse_last_gen_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogencourse',
            name='last_gen_time',
            field=models.DateTimeField(blank=True, default=b'2020-01-01 00:00'),
        ),
    ]
