# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-03 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_grade_gen', '0003_auto_20200603_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogencourse',
            name='last_gen_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
