# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-03 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_grade_gen', '0005_auto_20200603_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autogencourse',
            name='course_name',
            field=models.CharField(default=b'', max_length=100, null=True, verbose_name=b'Course Name'),
        ),
    ]
